### ISSUE TITLE
Добавление полей в другие таблицы?

### ISSUE THREAD

**Issue by DmitryFX** [Boshnik/ExtraFields#11]
Работа плагина с таблицами Ресурс, Пользователь и Пэйджблокс захардкожена, или доступные таблицы подтягиваются откуда-то автоматом?
Возможно ли с помощью этого плагина не создавать лишние поля в Ресурсе, а редактировать отдельно созданную таблицу?

**Comment by halftrainedharry** [comment]
It looks like the list of available tables is hard-coded.

The values for the "Table" dropdown when editing a field/tab:

https://github.com/Boshnik/ExtraFields/blob/ada72791f851b730c11ca4eb78245875f36860f9/assets/components/extrafields/js/mgr/misc/combo.js#L147-L157

The classes that are dynamically altered on the event "OnMODXInit":

https://github.com/Boshnik/ExtraFields/blob/ada72791f851b730c11ca4eb78245875f36860f9/core/components/extrafields/src/Events/OnMODXInit.php#L19-L33
