### ISSUE TITLE
Сбрасываются значения полей

### ISSUE THREAD

**Issue by webinmd** [Boshnik/ExtraFields#6]
При повторном редактировании настроек поля, некоторые значения сбрасываются. Пока были замечены:
- шаблоны 
- Скрыть время (у поля даты)

MODX 2.8.6. PHP 8.2

**Comment by Boshnik** [comment]
Шаблоны поправил.
Скрыть время не смог отловить ошибку, только если изменить тип поля, то тогда оно сбрасывается, но это логично.

Спасибо.

**Comment by webinmd** [comment]
С датой там если нажимать 2 раза на Сохранить, в обои всплывающих окошках

**Comment by Boshnik** [comment]
Ошибка исправлена
