### ISSUE TITLE
Ошибка при открытии поля для редактирования

### ISSUE THREAD

**Issue by ShevArtV** [Boshnik/ExtraFields#7]
При открытии любого поля на редактирование в журнале ошибок появляется следующая запись
"No foreign key definition for parentClass: efFieldAbs using relation alias: Tab"
Версия компонента 2.0.1-pl, Modx 2.8.7, PHP 7.4

**Comment by simbik** [comment]
А еще поля не появляются добавленные в разделе Пользователей. Вкладки появляются, поля нет.

**Comment by halftrainedharry** [comment]
> "No foreign key definition for parentClass: efFieldAbs using relation alias: Tab"

The error message gets generated in this line of the code:

https://github.com/Boshnik/ExtraFields/blob/ada72791f851b730c11ca4eb78245875f36860f9/core/components/extrafields/processors/mgr/abs/getlist.class.php#L37

The code tries to use the relationship `Tab` (class `efFieldAbs`) from the schema, that doesn't exist.

https://github.com/Boshnik/ExtraFields/blob/ada72791f851b730c11ca4eb78245875f36860f9/core/components/extrafields/model/schema/extrafields.mysql.schema.xml#L87-L90

The relationship could be added to the schema and the class files regenerated, but probably this whole code block is unnecessary

https://github.com/Boshnik/ExtraFields/blob/ada72791f851b730c11ca4eb78245875f36860f9/core/components/extrafields/processors/mgr/abs/getlist.class.php#L36-L47

as the fields 'tab' and 'category' doesn't seem to get used in the grid:

https://github.com/Boshnik/ExtraFields/blob/ada72791f851b730c11ca4eb78245875f36860f9/assets/components/extrafields/js/mgr/widgets/abs/grid.js#L111
